[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn salesmgt.wsgi:application --bind 0.0.0.0:8000"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "always"

[environment]
NIXPACKS_PYTHON_VERSION = "3.11"