# railway.toml

[deploy]
# The startCommand is now handled by the Dockerfile's CMD
healthcheckPath = "/health/" # Ensure this URL exists in your urls.py!
healthcheckTimeout = 300
restartPolicyType = "always"