[build]
builder = "nixpacks"

[deploy]
# Use a simple command to start the application using the new start.sh script.
# This script will handle the migrations and static file collection first.
startCommand = "./start.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "always"

[environment]
NIXPACKS_PYTHON_VERSION = "3.11"