[build]
builder = "nixpacks"

[deploy]
startCommand = "cd salesmgt && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn salesmgt.wsgi --log-file - --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "always"

[environment]
NIXPACKS_PYTHON_VERSION = "3.11"