# Generated by Django 5.2.6 on 2025-09-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiring_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
