# Generated by Django 5.2.6 on 2025-10-01 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
        ('store', '0002_alter_item_expiring_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='location',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='accounts.customer', verbose_name='Customer'),
        ),
    ]
